name: Documentation

on:
  push:
    branches:
      - main
  pull_request:

# Cancel any in-progress run on the same branch when a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  check:
    name: Docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "ci-ubuntu-latest"

      - name: Run docs-tests
        run: cargo test --workspace --locked --doc --all-features

      - name: Build docs
        run: cargo doc --no-deps --locked --workspace --all-features
